#!/bin/bash

SCRIPT_DIR=`dirname $0`

cd $SCRIPT_DIR

if [ ! -f $SCRIPT_DIR/play-run.conf ]; then
  echo "play-run.conf config file missing!"
  exit 1
fi

source $SCRIPT_DIR/play-run.conf

if [ "$http_port" == "" ]; then
  echo "run.conf must have an http_port defined"
  exit 1
fi

PLAY_DIR=`pwd`
LIB_DIR=`readlink $PLAY_DIR/play-current`
STDOUT_LOG=$PLAY_DIR/logs/stdout.log

# if RUNNING_PID file exists, verify if that process is still running
if [ -f $PLAY_DIR/RUNNING_PID ]; then
  echo "RUNNING_PID file exists; verifying if app still running..."
  PLAY_PID=`cat $PLAY_DIR/RUNNING_PID`
  if ps -p $PLAY_PID > /dev/null; then
    echo "application started: pid $PLAY_PID already exists" >> $STDOUT_LOG 
    exit 0
  else
    # pid no longer exists, delete the pid file
    echo "deleting RUNNING_PID file from previous run" >> $STDOUT_LOG
    rm -f $PLAY_DIR/RUNNING_PID
  fi
fi

exec java -Dconfig.file=prod.conf -Dhttp.port=$http_port -cp "$LIB_DIR/*" play.core.server.NettyServer $PLAY_DIR/ >$STDOUT_LOG 2>&1
